openapi: 3.0.3
info:
  title: Greeter API
  description: The greeting service definition.
  version: 0.0.1
paths:
  '/greeter/{name}':
    get:
      tags:
        - Greeter
      description: Sends a greeting
      operationId: Greeter_SayHello
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
        - schema:
            type: string
          in: header
          name: From
        - schema:
            type: string
          in: query
          name: device
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/.greeter.v1.HelloReply'
components:
  schemas:
    .greeter.v1.HelloReply:
      type: object
      properties:
        message:
          type: string
      description: The response message containing the greetings
tags:
  - name: Greeter
